#!/system/bin/sh

########
#PATHS #
########
# Path where logs and setup is stored
LSPEED_DATA_DIR=/data/lspeed
LOG_DIR=$LSPEED_DATA_DIR/log
LOG=$LOG_DIR/main_log.log

# Path for executables and busybox
LSPEED=/system/etc/lspeed
BINARY_DIR=$LSPEED/binary
BUSYBOX=$BINARY_DIR/busybox

sendToLog() {
timeZone=$(getprop persist.sys.timezone)
printDate=$(TZ="$timeZone" $BUSYBOX date +"%H:%M:%S:%3N %d-%m-%Y")

echo "[$printDate] $1" >> $LOG
}

write() {
	#chmod 0644 "$1"
    echo "$2" > "$1"
}

lockFile() {
	chmod 0644 "$1"
    echo "$2" > "$1"
	chmod 0444 "$1"
}

if [ $1 = "prime" ]; then 
	if [ -e $2 ]; then
		if [ -e $2/up_rate_limit_us ]; then
			lockFile $2/up_rate_limit_us "1000"
			sendToLog "up_rate_limit_us=1000"
		fi
	
		if [ -e $2/down_rate_limit_us ]; then
			lockFile $2/down_rate_limit_us "5000"
			sendToLog "down_rate_limit_us=5000"
		fi
		
		if [ -e $2/hispeed_load ]; then
			lockFile $2/hispeed_load "90"
			sendToLog "hispeed_load=90"
		fi
		
		if [ -e $2/rate_limit_us ]; then
			lockFile $2/rate_limit_us "0"
			sendToLog "rate_limit_us=0"
		fi
		
	fi

elif [ $1 = "big" ]; then 
	if [ -e $2 ]; then
		if [ -e $2/up_rate_limit_us ]; then
			lockFile $2/up_rate_limit_us "1000"
			sendToLog "up_rate_limit_us=1000"
		fi
	
		if [ -e $2/down_rate_limit_us ]; then
			lockFile $2/down_rate_limit_us "5000"
			sendToLog "down_rate_limit_us=5000"
		fi
		
		if [ -e $2/hispeed_load ]; then
			lockFile $2/hispeed_load "90"
			sendToLog "hispeed_load=90"
		fi
		
		if [ -e $2/rate_limit_us ]; then
			lockFile $2/rate_limit_us "0"
			sendToLog "rate_limit_us=0"
		fi
		
	fi

elif [ $1 = "little" ]; then 
	if [ -e $2 ]; then
		if [ -e $2/up_rate_limit_us ]; then
			lockFile $2/up_rate_limit_us "1000"
			sendToLog "up_rate_limit_us=1000"
		fi
	
		if [ -e $2/down_rate_limit_us ]; then
			lockFile $2/down_rate_limit_us "3000"
			sendToLog "down_rate_limit_us=3000"
		fi
		
		if [ -e $2/hispeed_load ]; then
			lockFile $2/hispeed_load "85"
			sendToLog "hispeed_load=85"
		fi
		
		if [ -e $2/rate_limit_us ]; then
			lockFile $2/rate_limit_us "0"
			sendToLog "rate_limit_us=0"
		fi
		
	fi

elif [ $1 = "regular" ]; then 
	if [ -e $2 ]; then
		if [ -e $2/up_rate_limit_us ]; then
			lockFile $2/up_rate_limit_us "1000"
			sendToLog "up_rate_limit_us=1000"
		fi
	
		if [ -e $2/down_rate_limit_us ]; then
			lockFile $2/down_rate_limit_us "3000"
			sendToLog "down_rate_limit_us=3000"
		fi
		
		if [ -e $2/hispeed_load ]; then
			lockFile $2/hispeed_load "85"
			sendToLog "hispeed_load=85"
		fi
		
		if [ -e $2/rate_limit_us ]; then
			lockFile $2/rate_limit_us "0"
			sendToLog "rate_limit_us=0"
		fi
	fi
fi
